# Generated by Django 5.1.3 on 2024-12-10 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVehiculo',
            fields=[
                ('id_colorvehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('color_vehiculo', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosProtegido',
            fields=[
                ('id_datosprotegido', models.AutoField(primary_key=True, serialize=False)),
                ('cronos', models.CharField(blank=True, max_length=70, null=True)),
                ('tipo_documento', models.IntegerField(blank=True, null=True)),
                ('nuip', models.IntegerField(blank=True, null=True)),
                ('fecha_expedicion', models.CharField(blank=True, max_length=10, null=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=70, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=70, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=70, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=70, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=70, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSicp',
            fields=[
                ('id_estadosicp', models.AutoField(primary_key=True, serialize=False)),
                ('estado_sicp', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id_marcavehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('marca_vehiculo', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id_tipovehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('contacto', models.BigIntegerField(blank=True, null=True)),
                ('id_datosprotegido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='sicp.datosprotegido')),
            ],
        ),
        migrations.AddField(
            model_name='datosprotegido',
            name='departamento',
            field=models.ForeignKey(blank=True, db_column='departamento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sicp.departamento'),
        ),
        migrations.CreateModel(
            name='Esquema',
            fields=[
                ('id_esquema', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_ruta', models.IntegerField(blank=True, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=25, null=True)),
                ('resuelve', models.TextField(blank=True, null=True)),
                ('id_datosprotegido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esquemas', to='sicp.datosprotegido')),
            ],
        ),
        migrations.AddField(
            model_name='datosprotegido',
            name='estado',
            field=models.ForeignKey(blank=True, db_column='estado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sicp.estadosicp'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipios', to='sicp.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='datosprotegido',
            name='municipio',
            field=models.ForeignKey(blank=True, db_column='municipio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sicp.municipio'),
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(blank=True, max_length=70, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=70, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=70, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=70, null=True)),
                ('id_datosprotegido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familiares', to='sicp.datosprotegido')),
                ('id_parentesco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familiares', to='sicp.parentesco')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaProteccion',
            fields=[
                ('id_personaproteccion', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(blank=True, max_length=70, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=70, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=70, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=70, null=True)),
                ('tipo_documento', models.IntegerField(blank=True, null=True)),
                ('nuip', models.IntegerField(blank=True, null=True)),
                ('fecha_expedicion', models.CharField(blank=True, max_length=10, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('id_esquema', models.ForeignKey(blank=True, db_column='id_esquema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_proteccion', to='sicp.esquema')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(blank=True, max_length=6, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='sicp.colorvehiculo')),
                ('id_esquema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='sicp.esquema')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='sicp.marcavehiculo')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='sicp.tipovehiculo')),
            ],
        ),
    ]
