# Generated by Django 5.1.3 on 2024-11-20 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosProtegido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=70)),
                ('segundo_nombre', models.CharField(max_length=70)),
                ('primer_apellido', models.CharField(max_length=70)),
                ('segundo_apellido', models.CharField(max_length=70)),
                ('lider_asignado', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.PositiveSmallIntegerField()),
                ('municipio', models.PositiveIntegerField()),
                ('cedula', models.CharField(blank=True, max_length=11, null=True)),
                ('enlace_ponal', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_ruta', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(blank=True, max_length=11, null=True)),
                ('id_protegido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='sicp.datosprotegido')),
            ],
        ),
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=6, null=True)),
                ('id_protegido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placas', to='sicp.datosprotegido')),
            ],
        ),
    ]
