# Generated by Django 5.1.3 on 2024-12-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaproteccion',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
