# Generated by Django 5.1.3 on 2024-12-11 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicp', '0002_alter_esquema_id_datosprotegido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esquema',
            name='id_datosprotegido',
            field=models.ForeignKey(blank=True, db_column='id_datosprotegido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esquemas', to='sicp.datosprotegido'),
        ),
    ]
