# Generated by Django 5.1.3 on 2024-12-10 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicp', '0003_alter_personaproteccion_nuip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='id_esquema',
            field=models.ForeignKey(blank=True, db_column='id_esquema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='sicp.esquema'),
        ),
    ]
