# Generated by Django 5.1.3 on 2024-12-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicp', '0004_alter_vehiculo_id_esquema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.ForeignKey(blank=True, db_column='color', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='sicp.colorvehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(blank=True, db_column='marca', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='sicp.marcavehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.ForeignKey(blank=True, db_column='tipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='sicp.tipovehiculo'),
        ),
    ]
