# Generated by Django 5.0.7 on 2024-11-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datossesp',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='datossesp',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
