# Generated by Django 5.0.7 on 2024-11-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesp', '0002_datossesp_cedula_alter_datossesp_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosSesp',
        ),
    ]
